### ISSUE TITLE
Possible bug in SQL query processing/parsing

### ISSUE THREAD

**Issue by iouri-forusall** [arkflow-rs/arkflow#238]
**Describe the bug**
The SQL query in the configuration fails due to case sensitivity issues with the column name 'productId'. The query attempts to use 'productid' (lowercase) while the JSON input field is 'productId' (camelCase).

While using double quotes in the query configuration does fix it, I am not sure if it's the expected behavior, otherwise please close this issue:

This works:

```yaml
processors:
  - type: "sql"
    query: 'SELECT "productId" FROM flow'
```

**To Reproduce**
1. Create a configuration file `config.yaml` with the following content:
```yaml
logging:
  level: info
  format: text
streams:
  - input:
      type: "http"
      address: '0.0.0.0:8080'
      path: '/'
    pipeline:
      thread_num: 4
      processors:
        - type: "json_to_arrow"
        - type: "sql"
          query: "SELECT productId FROM flow"
    output:
      type: "stdout"
```

2. Start arkflow with this configuration:
```bash
arkflow --config config.yaml
```

3. Send the following curl request to the server:
```bash
curl "http://localhost:8080" \
  -H "Content-Type: application/json" \
  -d '{
    "productId": 1,
    "product_name": "An ice sculpture"
  }'
```

4. Observe the error in the logs

**Expected behavior**
The query should successfully process the JSON input and extract the 'productId' field. The SQL query should either:
1. Match the exact case of the JSON field name ('productId'), or
2. Have case-insensitive column name matching enabled

**Error Message**
```
2025-04-17T04:31:45.109446Z ERROR arkflow_core::stream: Process errors: Execution query error: Schema error: No field named flow.productid. Column names are case sensitive. You can use double quotes to refer to the "flow.productid" column or set the datafusion.sql_parser.enable_ident_normalization configuration. Did you mean 'flow.productId'?.
```
